class ComposerSeed
  def self.composers
    composers = [
      'Ludwig van Beethoven',
      'Franz Joseph Haydn',
      'Wolfgang Amadeus Mozart',
      'Gustav Mahler',
      'Johannes Brahms',
      'Maurice Ravel',
      'Claude Debussy',
      'Dmitri Shostakovich',
      'Igor Stravinsky',
      'Sergei Rachmaninoff',
      'Leonard Bernstein',
      'Johann Christian Bach',
      'Carl Phillip Emanuel Bach',
      'Samuel Barber',
      'Alban Berg',
      'Luciano Berio',
      'Georges Bizet',
      'Alexander Borodin',
      'Pierre Boulez',
      'Benjamin Britten',
      'Anton Bruckner',
      'Ferruccio Busoni',
      'Dieterich Buxtehude',
      'John Cage',
      'Ellott Carter',
      'Ernest Chausson',
      'Emmanuel Chabrier',
      'Frederic Chopin',
      'Muzio Clementi',
      'Aaron Copland',
      'Louis Couperin',
      'Anton Diabelli',
      'Edward Elgar',
      'Cesar Franck',
      'Girolamo Frescobaldi',
      'Alexander Glazunov',
      'Mikhail Glinka',
      'Christoph Willibald Gluck',
      'Percy Grainger',
      'Charles Gounod',
      'Edvard Grieg',
      'George Frideric Handel',
      'Franz Joseph Haydn',
      'Paul Hindemith',
      'Charles Ives',
      'Dmitry Kabalevsky',
      'Fritz Kreisler',
      'Friedrich Kuhlau',
      'Gyorgy Ligeti',
      'Franz Liszt',
      'Guillaume de Machaut',
      'Gustav Mahler',
      'Felix Mendelssohn',
      'Olivier Messiaen',
      'Darius Milhaud',
      'Jacques Offenbach',
      'Johann Pachelbel',
      'Francis Poulenc',
      'Sergei Prokofiev',
      'Henry Purcell',
      'Giacomo Puccini',
      'Maurice Ravel',
      'Nikolai Rimsky-Korsakov',
      'Gioachino Rossini',
      'Anton Salieri',
      'Erik Satie',
      'Alessandro Scarlatti',
      'Arnold Schoenberg',
      'Franz Schubert',
      'Robert Schumann',
      'Dmitri Shostakovich',
      'Jean Sibelius',
      'Karlheinz Stockhausen',
      'Richard Strauss',
      'Igor Stravinsky',
      'Pyotr Ilyich Tchaikovsky',
      'Ralph Vaughn Williams',
      'Giuseppe Verdi',
      'Antonio Vivaldi',
      'Richard Wagner',
      'Anton Webern'
    ];
  end

  def self.composer
    composers.sample
  end
end
